/**
 * Sandbox provider interface.
 *
 * Defines a pluggable abstraction for sandbox providers (Modal, Fly.io, Docker, etc.)
 * enabling unit testing and future provider support.
 */

import type { HarnessId } from "@open-inspect/shared/harnesses";
import type { ImageBuildScopeKind } from "@open-inspect/shared/types/image-builds";
import type { SandboxSettings } from "@open-inspect/shared/types/integrations";
import type { CorrelationContext } from "../logger";
import { RequestDeadlineError } from "./request-deadline";
import type { McpServerConfig } from "@open-inspect/shared/types/integrations";

/** Default sandbox lifetime in seconds (2 hours). */
export const DEFAULT_SANDBOX_TIMEOUT_SECONDS = 7200;

/**
 * Provider-neutral configuration for triggering an image build inside a
 * provider session. Every supported provider follows the same
 * create-bind-launch contract: create the build sandbox, bind its provider
 * session id via `onProviderSessionCreated`, then launch the build runtime.
 * Providers that need extra fields extend this type (see
 * ModalImageBuildTriggerConfig).
 */
export interface ImageBuildProviderTriggerConfig {
  buildId: string;
  scopeKind: ImageBuildScopeKind;
  /** Build scope id; used only for sandbox naming/labels. */
  scopeId: string;
  /** Repositories in position order ([0] = primary), cloned at their base branches. */
  repositories: Array<{ repoOwner: string; repoName: string; baseBranch: string }>;
  callbackUrl: string;
  failureCallbackUrl: string;
  callbackToken: string;
  userEnvVars?: Record<string, string>;
  cloneToken?: string;
  buildExecutionTimeoutSeconds: number;
  /**
   * Provider-session lifetime in seconds, including deferred finalization
   * headroom. Always resolved by the adapter layer
   * (resolveImageBuildProviderSessionTimeoutSeconds) — providers apply it
   * verbatim instead of choosing their own default.
   */
  providerSessionTimeoutSeconds: number;
  onProviderSessionCreated: (providerSessionId: string) => Promise<void>;
  correlation: CorrelationContext;
}

/**
 * Capabilities supported by a sandbox provider.
 * Providers can support different feature sets.
 */
export interface SandboxProviderCapabilities {
  /** Whether explicit sandbox session lifetimes are enforced by this provider. */
  supportsSandboxTimeout: boolean;
  /** Whether the provider supports filesystem snapshots */
  supportsSnapshots: boolean;
  /** Whether the provider supports restoring from snapshots */
  supportsRestore: boolean;
  /** Whether the provider can resume a previously stopped sandbox in place */
  supportsPersistentResume?: boolean;
  /** Whether the provider can stop a sandbox explicitly via API */
  supportsExplicitStop?: boolean;
  /** An ordinary checkpoint must enter the terminal shutdown flow first. */
  snapshotRequiresShutdown?: boolean;
  /**
   * The provider can reset a sandbox's continuous-run window in place,
   * preserving memory and processes (E2B pause→connect). Providers whose
   * pause is a filesystem-only snapshot cannot: a refresh there would lose
   * the running turn, which is exactly what the refresh exists to avoid.
   */
  supportsRuntimeWindowRefresh?: boolean;
}

export type SandboxLifetime =
  | {
      kind: "finite";
      expiresAtMs: number;
      observedAtMs: number;
      source: "provider" | "conservative_start_bound";
    }
  | { kind: "none"; observedAtMs: number }
  | { kind: "unknown"; observedAtMs: number; reason: string };

export interface PendingSandboxAllocation {
  reference: string;
  lifetime: Extract<SandboxLifetime, { kind: "finite" }>;
}

/**
 * One member repository of a session, in position order (first = primary).
 * Mirrors the runtime's SessionRepositoryConfig, whose snake_case wire form
 * (with baseBranch renamed to `branch`) is produced by
 * toRepositoryConfigPayload.
 */
export interface SessionRepositoryInfo {
  repoOwner: string;
  repoName: string;
  /** Base branch to clone (resolved at session create; never null). */
  baseBranch: string;
  /** Immutable session-start commit used by the Changes capture protocol. */
  baseSha?: string | null;
}

/**
 * Configuration for creating a new sandbox.
 */
export interface CreateSandboxConfig {
  /** Session ID for WebSocket routing */
  sessionId: string;
  /** Expected sandbox ID (generated by control plane) */
  sandboxId: string;
  /** Repository owner */
  repoOwner: string | null;
  /** Repository name */
  repoName: string | null;
  /** Control plane URL for sandbox callbacks */
  controlPlaneUrl: string;
  /** Authentication token for sandbox */
  sandboxAuthToken: string;
  /** Agent harness the session runs on */
  harness: HarnessId;
  /** LLM provider (e.g., "anthropic") */
  provider: string;
  /** LLM model (e.g., "claude-sonnet-4-5") */
  model: string;
  /** User-provided environment variables (repo secrets) */
  userEnvVars?: Record<string, string>;
  /** The agent's own conversation id, for resumption */
  agentSessionId?: string;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /**
   * Opaque provider image ID of a pre-built image — a repo image for
   * single-repo sessions, an environment image for environment sessions.
   * Both boot through the same provider plumbing (FROM_REPO_IMAGE flags).
   */
  prebuiltImageId?: string | null;
  /** Git SHA the image was built from (the primary repository's for environment images) */
  prebuiltImageSha?: string | null;
  /** Sandbox lifetime in seconds. Defaults to DEFAULT_SANDBOX_TIMEOUT_SECONDS on Modal. */
  timeoutSeconds?: number;
  /** Git branch to work on (defaults to repo's default branch) */
  branch?: string | null;
  /** Whether to enable code-server (browser-based editor) in the sandbox */
  codeServerEnabled?: boolean;
  /** Whether to enable browser-based VNC access to the sandbox */
  vncEnabled?: boolean;
  /**
   * Whether to install the agent-initiated slack-notify tool. Fixed for the
   * lifetime of the sandbox; per-call authorization is re-evaluated by the
   * control-plane endpoint.
   */
  agentSlackNotifyEnabled?: boolean;
  /** MCP servers to inject into the agent session */
  mcpServers?: McpServerConfig[];
  /** Sandbox settings (tunnel ports, etc.) resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /** Previous logical allocation identity, used by providers supporting ambiguous-create recovery. */
  retireSandboxId?: string | null;
  /** Generation reservation time used to bound pending provider launches. */
  generationCreatedAtMs?: number;
  /**
   * Ordered member list for multi-repo sessions. Only set when the session
   * has more than one member — single-repo sessions keep the scalar
   * repoOwner/repoName/branch wire form (the runtime synthesizes its
   * one-entry list from them). Working-branch names are not part of this
   * config: they are derived lazily at PR-creation time
   * (pull-request-service) and travel in per-repo push specs.
   */
  repositories?: SessionRepositoryInfo[];
}

/** Complete browser-desktop access credential returned by sandbox providers. */
export interface VncAccess {
  url: string;
  password: string;
}

/** Build a complete VNC access credential, or omit incomplete provider data. */
export function createVncAccess(
  url: string | undefined,
  password: string | undefined
): VncAccess | undefined {
  return url && password ? { url, password } : undefined;
}

/**
 * Result of creating a sandbox.
 */
export interface CreateSandboxResult {
  /** The sandbox ID (should match expected ID from config) */
  sandboxId: string;
  /** Provider's internal object ID (e.g., Modal's object ID for snapshot API) */
  providerObjectId?: string;
  /** Creation timestamp */
  createdAt: number;
  lifetime: SandboxLifetime;
  /** Code-server tunnel URL (if available) */
  codeServerUrl?: string;
  /** Code-server password (if available) */
  codeServerPassword?: string;
  /** ttyd proxy tunnel URL (if available) */
  ttydUrl?: string;
  /** Complete browser-based VNC credential (if available) */
  vncAccess?: VncAccess;
  /** Tunnel URLs for extra ports (port -> URL mapping) */
  tunnelUrls?: Record<string, string>;
}

/**
 * Configuration for restoring a sandbox from a snapshot.
 */
export interface RestoreConfig {
  /** Snapshot image ID to restore from */
  snapshotImageId: string;
  /** Session ID for WebSocket routing */
  sessionId: string;
  /** Expected sandbox ID */
  sandboxId: string;
  /** Authentication token for sandbox */
  sandboxAuthToken: string;
  /** Control plane URL for sandbox callbacks */
  controlPlaneUrl: string;
  /** Repository owner */
  repoOwner: string | null;
  /** Repository name */
  repoName: string | null;
  /** Agent harness the session runs on */
  harness: HarnessId;
  /** LLM provider (e.g., "anthropic") */
  provider: string;
  /** LLM model (e.g., "claude-sonnet-4-5") */
  model: string;
  /** User-provided environment variables (repo secrets) */
  userEnvVars?: Record<string, string>;
  /** Sandbox lifetime in seconds. Defaults to DEFAULT_SANDBOX_TIMEOUT_SECONDS. */
  timeoutSeconds?: number;
  /** Git branch to work on (defaults to repo's default branch) */
  branch?: string | null;
  /** MCP servers to inject into the sandbox */
  mcpServers?: McpServerConfig[];
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Whether to enable code-server (browser-based editor) in the sandbox */
  codeServerEnabled?: boolean;
  /** Whether to enable browser-based VNC access to the sandbox */
  vncEnabled?: boolean;
  /** Resolved fresh on each restore — see CreateSandboxConfig. */
  agentSlackNotifyEnabled?: boolean;
  /** Sandbox settings (tunnel ports, etc.) resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /** Previous logical allocation identity, used by providers supporting ambiguous-create recovery. */
  retireSandboxId?: string | null;
  /** Generation reservation time used to bound pending provider launches. */
  generationCreatedAtMs?: number;
  /** Multi-repo member list — see CreateSandboxConfig. */
  repositories?: SessionRepositoryInfo[];
}

/**
 * Result of restoring a sandbox from a snapshot.
 */
interface RestoreResultFields {
  /** Sandbox ID if successful */
  sandboxId?: string;
  /** Provider's internal object ID (e.g., Modal's object ID for snapshot API) */
  providerObjectId?: string;
  /** Error message if failed */
  error?: string;
  /** Code-server tunnel URL (if available) */
  codeServerUrl?: string;
  /** Code-server password (if available) */
  codeServerPassword?: string;
  /** ttyd proxy tunnel URL (if available) */
  ttydUrl?: string;
  /** Complete browser-based VNC credential (if available) */
  vncAccess?: VncAccess;
  /** Tunnel URLs for extra ports (port -> URL mapping) */
  tunnelUrls?: Record<string, string>;
}

export type RestoreResult =
  | (RestoreResultFields & {
      /** Whether the restore succeeded */
      success: true;
      lifetime: SandboxLifetime;
    })
  | (RestoreResultFields & {
      /** Whether the restore succeeded */
      success: false;
      lifetime?: never;
    });

/**
 * Configuration for taking a sandbox snapshot.
 */
export interface SnapshotConfig {
  /** Provider's internal object ID (e.g., Modal's object ID) */
  providerObjectId: string;
  /** Session ID for context */
  sessionId: string;
  /** Reason for the snapshot (e.g., "inactivity_timeout", "execution_complete") */
  reason: string;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Optional caller deadline for long-running provider artifact creation. */
  signal?: AbortSignal;
  /** Absolute caller deadline shared by every nested provider operation. */
  deadlineAtMs?: number;
}

/**
 * Result of taking a sandbox snapshot.
 */
export interface SnapshotResult {
  /** Whether the snapshot succeeded */
  success: boolean;
  /** Snapshot image ID if successful */
  imageId?: string;
  /** Error message if failed */
  error?: string;
  /** True when snapshot creation itself stopped the source sandbox. */
  sourceStopped?: boolean;
  /** Immutable source ID to retire after committing the snapshot receipt. */
  sourceObjectId?: string;
}

/**
 * Configuration for resuming a previously stopped sandbox.
 */
export interface ResumeConfig {
  /** Provider's internal object ID (e.g., Daytona sandbox ID) */
  providerObjectId: string;
  /** Session ID for context */
  sessionId: string;
  /** Control-plane logical sandbox ID used for bridge auth */
  sandboxId: string;
  /** Sandbox lifetime in seconds from control-plane policy */
  timeoutSeconds?: number;
  /** Whether code-server should be exposed */
  codeServerEnabled?: boolean;
  /** Whether browser-based VNC access should be exposed */
  vncEnabled?: boolean;
  /** Sandbox settings (tunnel ports, etc.) resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
}

/**
 * Result of resuming a previously stopped sandbox.
 */
interface ResumeResultFields {
  /** Provider's internal object ID, if it changed during recovery */
  providerObjectId?: string;
  /** Error message if resume failed */
  error?: string;
  /** Whether the caller should fall back to a fresh create */
  shouldSpawnFresh?: boolean;
  /** Code-server tunnel URL (if available) */
  codeServerUrl?: string;
  /** Code-server password (if available) */
  codeServerPassword?: string;
  /** ttyd proxy tunnel URL (if available) */
  ttydUrl?: string;
  /** Complete browser-based VNC credential (if available) */
  vncAccess?: VncAccess;
  /** Tunnel URLs for extra ports (port -> URL mapping) */
  tunnelUrls?: Record<string, string>;
}

export type ResumeResult =
  | (ResumeResultFields & {
      /** Whether the resume succeeded */
      success: true;
      lifetime: SandboxLifetime;
    })
  | (ResumeResultFields & {
      /** Whether the resume succeeded */
      success: false;
      lifetime?: never;
    });

/**
 * Configuration for explicitly stopping a sandbox.
 */
export interface StopConfig {
  /** Provider's internal object ID (e.g., Daytona sandbox ID) */
  providerObjectId: string;
  /** Session ID for context */
  sessionId: string;
  /** Reason for the stop operation */
  reason: string;
  /** Whether the provider-owned state must remain resumable or be destroyed. */
  intent: "preserve" | "destroy";
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Optional caller deadline for provider cleanup. */
  signal?: AbortSignal;
  /** Absolute caller deadline shared by every nested provider operation. */
  deadlineAtMs?: number;
  /** Reservation time of the generation being stopped, if known. */
  generationCreatedAtMs?: number;
}

/**
 * Result of explicitly stopping a sandbox.
 */
export interface StopResult {
  /** Whether the stop succeeded */
  success: boolean;
  /** Error message if stop failed */
  error?: string;
}

/** Combine caller cancellation with an absolute provider-operation deadline. */
export function signalUntilDeadline(
  deadlineAtMs: number | undefined,
  signal?: AbortSignal
): AbortSignal | undefined {
  if (deadlineAtMs === undefined) return signal;
  const remainingMs = deadlineAtMs - Date.now();
  const deadlineSignal =
    remainingMs <= 0
      ? AbortSignal.abort(new DOMException("Provider operation deadline exceeded", "TimeoutError"))
      : AbortSignal.timeout(remainingMs);
  return signal ? AbortSignal.any([signal, deadlineSignal]) : deadlineSignal;
}

/**
 * Error classification for circuit breaker decisions.
 *
 * Only permanent failures should count toward the circuit breaker threshold.
 * Transient failures (network issues, timeouts) are logged but don't trip the breaker.
 *
 * Transient errors (do NOT count toward circuit breaker):
 * - ETIMEDOUT, ECONNRESET, ECONNREFUSED
 * - HTTP 502, 503, 504 (Bad Gateway, Service Unavailable, Gateway Timeout)
 * - "fetch failed" / network errors
 *
 * Permanent errors (DO count toward circuit breaker):
 * - HTTP 400, 401, 403, 422 (Bad Request, Unauthorized, Forbidden, Unprocessable)
 * - Invalid configuration
 * - Resource quota exceeded
 */
export type SandboxErrorType = "transient" | "permanent";

/**
 * Custom error class for sandbox provider operations.
 *
 * Includes error type classification for circuit breaker handling.
 * The circuit breaker only counts permanent errors toward its threshold.
 */
export class SandboxProviderError extends Error {
  constructor(
    message: string,
    public readonly errorType: SandboxErrorType,
    public readonly cause?: Error
  ) {
    super(message);
    this.name = "SandboxProviderError";
    // Maintain proper stack trace in V8 environments
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, SandboxProviderError);
    }
  }

  /**
   * Check if an HTTP status code indicates a transient error.
   */
  static isTransientStatus(status: number): boolean {
    return status === 502 || status === 503 || status === 504;
  }

  /**
   * Check if an error is likely a transient network error.
   */
  static isTransientNetworkError(error: unknown): boolean {
    if (error instanceof RequestDeadlineError) return true;
    if (error instanceof Error) {
      const message = error.message.toLowerCase();
      return (
        message.includes("fetch failed") ||
        message.includes("etimedout") ||
        message.includes("econnreset") ||
        message.includes("econnrefused") ||
        message.includes("network") ||
        message.includes("timeout")
      );
    }
    return false;
  }

  /**
   * Create a SandboxProviderError from a fetch error or HTTP response.
   */
  static fromFetchError(message: string, error: unknown, status?: number): SandboxProviderError {
    // Classify based on HTTP status if available
    if (status !== undefined) {
      const errorType = SandboxProviderError.isTransientStatus(status) ? "transient" : "permanent";
      return new SandboxProviderError(
        message,
        errorType,
        error instanceof Error ? error : undefined
      );
    }

    // Classify based on error type
    const errorType = SandboxProviderError.isTransientNetworkError(error)
      ? "transient"
      : "permanent";
    return new SandboxProviderError(message, errorType, error instanceof Error ? error : undefined);
  }
}

/** A rejected execution; a non-null handle remains a cleanup obligation. */
export class SandboxLaunchRejectedError extends SandboxProviderError {
  constructor(
    message: string,
    readonly providerObjectId: string | null,
    cause?: Error
  ) {
    super(message, "permanent", cause);
    this.name = "SandboxLaunchRejectedError";
  }
}

/** The provider confirmed that the selected prebuilt artifact cannot be restored. */
export class PrebuiltImageUnavailableError extends SandboxProviderError {
  constructor(message: string, cause?: Error) {
    super(message, "permanent", cause);
    this.name = "PrebuiltImageUnavailableError";
  }
}

/**
 * A prebuilt image the provider could not confirm as usable right now: it is
 * still being brought back from cold storage, or the provider could not be
 * reached to say.
 *
 * Transient, and deliberately not a `PrebuiltImageUnavailableError`: only an
 * answer about the artifact itself — that it is missing, or in a state it
 * never leaves — may retire an image, so a slow activation or an unreachable
 * API does not throw away a perfectly good prebuild. The image is not proven
 * unusable, so it stays in rotation; this spawn fails transiently.
 */
export class PrebuiltImageActivationPendingError extends SandboxProviderError {
  constructor(message: string, cause?: Error) {
    super(message, "transient", cause);
    this.name = "PrebuiltImageActivationPendingError";
  }
}

/**
 * Sandbox provider interface.
 *
 * Defines the contract for sandbox lifecycle operations.
 * Implementations wrap provider-specific APIs (Modal, Fly.io, Docker, etc.)
 *
 * Error handling:
 * - Methods should throw SandboxProviderError with appropriate errorType
 * - "transient" errors (network issues) don't count toward circuit breaker
 * - "permanent" errors (config issues) do count toward circuit breaker
 *
 * @example
 * ```typescript
 * const provider: SandboxProvider = new ModalSandboxProvider(client);
 *
 * try {
 *   const result = await provider.createSandbox(config);
 *   console.log("Created:", result.sandboxId);
 * } catch (e) {
 *   if (e instanceof SandboxProviderError && e.errorType === "permanent") {
 *     // Increment circuit breaker
 *   }
 *   // Both types set sandbox status to "failed"
 * }
 * ```
 */
export interface SandboxProvider {
  /** Provider name for logging and debugging */
  readonly name: string;

  /** Provider capabilities */
  readonly capabilities: SandboxProviderCapabilities;

  /** Reference and lifetime to persist before launch; neither confirms startup succeeded. */
  pendingSandboxAllocation?(
    config: Pick<
      CreateSandboxConfig,
      "sessionId" | "sandboxId" | "generationCreatedAtMs" | "timeoutSeconds"
    >
  ): PendingSandboxAllocation | undefined;

  /**
   * Create a new sandbox.
   *
   * @param config - Sandbox configuration
   * @returns Creation result with sandbox ID and status
   * @throws SandboxProviderError with errorType for circuit breaker handling
   */
  createSandbox(config: CreateSandboxConfig): Promise<CreateSandboxResult>;

  /**
   * Restore a sandbox from a filesystem snapshot.
   *
   * Only available if `capabilities.supportsRestore` is true.
   *
   * @param config - Restore configuration with snapshot image ID
   * @returns Result indicating success or failure
   * @throws SandboxProviderError with errorType for circuit breaker handling
   */
  restoreFromSnapshot?(config: RestoreConfig): Promise<RestoreResult>;

  /**
   * Resume a previously stopped sandbox in place.
   *
   * Only available if `capabilities.supportsPersistentResume` is true.
   */
  resumeSandbox?(config: ResumeConfig): Promise<ResumeResult>;

  /**
   * Reset a running sandbox's continuous-run window in place (E2B
   * pause→connect), returning the fresh lifetime. Called between turns only;
   * a provider may reject or throw, leaving the lifetime drain as the
   * safety net.
   */
  refreshRuntimeWindow?(providerObjectId: string, timeoutSeconds?: number): Promise<SandboxLifetime>;

  /**
   * Take a filesystem snapshot of the sandbox.
   *
   * Only available if `capabilities.supportsSnapshots` is true.
   *
   * @param config - Snapshot configuration with provider object ID
   * @returns Result with snapshot image ID if successful
   * @throws SandboxProviderError with errorType for error handling
   */
  takeSnapshot?(config: SnapshotConfig): Promise<SnapshotResult>;

  /**
   * Stop a sandbox explicitly via the provider API.
   *
   * Only available if `capabilities.supportsExplicitStop` is true.
   */
  stopSandbox?(config: StopConfig): Promise<StopResult>;
}
